development:
  application_title: 'Pine'
  application_port: 1337
  submodule:
    path: 'Pine_Needles/contents/articles/'
    branch: 'development'
    remote: 'origin'
    
  
test:
  application_title: 'Pine'
  application_port: ''
  submodule:
    path: 'Pine_Needles/contents/articles/'
    branch: 'development'
    remote: 'origin'
    
  
  
production:
  application_title: 'Pine'
  application_port: 80
  submodule:
    path: 'Pine_Needles/contents/articles/'
    branch: 'master'
    remote: 'origin'
    